question_data = [
    {"text": "Python is a compiled language.", "answer": "False"},
    {"text": "HTML stands for Hypertext Markup Language.", "answer": "True"},
    {"text": "JavaScript is primarily used for server-side programming.", "answer": "False"},
    {"text": "CSS is used to style HTML documents.", "answer": "True"},
    {"text": "The 'print' function in Python outputs text to the console.", "answer": "True"},
    {"text": "A variable in programming cannot change its value.", "answer": "False"},
    {"text": "In Python, lists are ordered collections of items.", "answer": "True"},
    {"text": "The 'if' statement is used for making decisions in code.", "answer": "True"},
    {"text": "An array can hold elements of different data types.", "answer": "False"},
    {"text": "Java is a platform-independent language.", "answer": "True"},
    {"text": "A loop is used to execute a block of code repeatedly.", "answer": "True"},
    {"text": "Python uses indentation to define code blocks.", "answer": "True"},
    {"text": "The 'else' statement can be used without an 'if' statement.", "answer": "False"},
    {"text": "Functions in programming can return values.", "answer": "True"},
    {"text": "In C++, 'int' is used to declare integer variables.", "answer": "True"},
    {"text": "Comments in code are executed during runtime.", "answer": "False"},
    {"text": "The 'while' loop will continue until its condition is false.", "answer": "True"},
    {"text": "In Python, dictionaries are unordered collections of key-value pairs.", "answer": "True"},
    {"text": "SQL is used for managing relational databases.", "answer": "True"},
    {"text": "A syntax error occurs when the code is written correctly, but logic is wrong.", "answer": "False"},
    {"text": "In Java, the main method is the entry point of any program.", "answer": "True"},
    {"text": "In programming, an 'API' stands for Application Programming Interface.", "answer": "True"},
    {"text": "HTML can be used to create dynamic web applications.", "answer": "False"},
    {"text": "Git is a version control system.", "answer": "True"},
    {"text": "In JavaScript, 'undefined' means a variable has been declared but not assigned a value.", "answer": "True"},
    {"text": "A boolean data type can only hold one of two values: true or false.", "answer": "True"},
    {"text": "CSS can be used to create animations.", "answer": "True"},
    {"text": "Java uses a garbage collector to manage memory.", "answer": "True"},
    {"text": "In Python, tuples are mutable data structures.", "answer": "False"},
    {"text": "A 'for' loop is often used to iterate over a sequence.", "answer": "True"},
    {"text": "An exception is a runtime error that can be handled in code.", "answer": "True"},
    {"text": "In C#, the 'static' keyword means that a member belongs to the type itself rather than to a specific object.", "answer": "True"},
    {"text": "CSS selectors are used to apply styles to HTML elements.", "answer": "True"},
    {"text": "JavaScript is the same as Java.", "answer": "False"},
    {"text": "Python can be used for web development, data analysis, and artificial intelligence.", "answer": "True"},
    {"text": "An IDE stands for Integrated Development Environment.", "answer": "True"},
    {"text": "In programming, a 'bug' is a synonym for a feature.", "answer": "False"},
    {"text": "Java supports multiple inheritance.", "answer": "False"},
    {"text": "The term 'frontend' refers to the client-side of a web application.", "answer": "True"},
    {"text": "A class in OOP is a blueprint for creating objects.", "answer": "True"},
    {"text": "Python uses braces {} to define blocks of code.", "answer": "False"},
    {"text": "In SQL, the 'SELECT' statement is used to retrieve data from a database.", "answer": "True"},
    {"text": "A 'stack' is a data structure that follows the Last In, First Out (LIFO) principle.", "answer": "True"},
    {"text": "In Java, 'final' keyword is used to declare constants.", "answer": "True"},
    {"text": "HTML5 introduced new semantic elements like <header> and <footer>.", "answer": "True"},
    {"text": "In Python, the 'len()' function returns the length of a list.", "answer": "True"},
    {"text": "A 'query' is a request for information from a database.", "answer": "True"},
    {"text": "In Java, method overloading allows multiple methods with the same name but different parameters.", "answer": "True"},
    {"text": "In JavaScript, 'let' is used to declare variables with block scope.", "answer": "True"},
    {"text": "A 'boolean' can store any type of data.", "answer": "False"},
    {"text": "A function can be defined without a return statement.", "answer": "True"},
    {"text": "JSON stands for JavaScript Object Notation.", "answer": "True"},
    {"text": "CSS Grid is a layout system that allows for complex responsive web designs.", "answer": "True"},
    {"text": "In Python, 'None' is equivalent to 'null' in other languages.", "answer": "True"},
    {"text": "A web server's primary role is to send and receive email.", "answer": "False"},
    {"text": "In C++, pointers are used to reference memory addresses.", "answer": "True"},
    {"text": "The 'switch' statement is used as a shorthand for multiple 'if' statements.", "answer": "True"},
    {"text": "In HTML, the <script> tag is used to include JavaScript.", "answer": "True"},
    {"text": "React is a JavaScript library for building user interfaces.", "answer": "True"},
    {"text": "In Python, 'input()' reads user input as a string.", "answer": "True"},
    {"text": "XML is primarily used for styling web pages.", "answer": "False"},
    {"text": "The command line is a text-based interface to interact with the operating system.", "answer": "True"},
    {"text": "In CSS, 'margin' creates space inside an element's border.", "answer": "False"},
    {"text": "A 'kernel' is the core part of an operating system.", "answer": "True"},
    {"text": "In SQL, 'JOIN' is used to combine rows from two or more tables.", "answer": "True"},
    {"text": "In programming, 'refactoring' means rewriting code to improve its structure without changing its behavior.", "answer": "True"},
    {"text": "A 'constructor' is a special method used to create an instance of a class.", "answer": "True"},
    {"text": "In Python, 'break' is used to exit a loop.", "answer": "True"},
    {"text": "In Java, 'this' refers to the current object.", "answer": "True"},
    {"text": "A 'repository' is a storage location for software packages.", "answer": "True"},
    {"text": "In HTML, the <link> tag is used to connect CSS files.", "answer": "True"},
    {"text": "A database is a collection of organized data.", "answer": "True"},
    {"text": "In programming, an 'argument' is a value passed to a function.", "answer": "True"},
    {"text": "A 'debugger' is a tool used to find and fix errors in code.", "answer": "True"},
    {"text": "In Python, the 'map()' function applies a function to every item in an iterable.", "answer": "True"},
    {"text": "The 'return' statement is optional in a function.", "answer": "True"},
]
